### ISSUE TITLE
Implement keyboard smash features

### ISSUE THREAD

**Issue by LeoSilvaGomes** [PDA-FGA/Playground#15]
Epic: #14 

## Description

Migrate keyboard smash features function to the `playground` project

### Output

(dataframe original, dataframe result)

**dataframe original:** dataframe with the data will be processed (string)
**dataframe result:** dataframe with result of keyboard smash features about `dataframe original`

### Checklist
- [x] Add char_frequency feature
- [x] Add special_character_sequency feature
- [x] Add number_sequency feature
- [x] Add vowels_sequency feature
- [x] Add consoants_sequency feature

**Comment by RochaCarla** [comment]
- Pre processing -

- the pre-processed addresses database + keyboard smashing features for STREET_ADDRESS_1 and STREET_ADDRESS_2 concatenated
- remove null values 

Features extracted:


- street_address_sequence_vowels_concat
- street_address_sequence_consonants_concat
- street_address_sequence_special_characters_concat
- ksmash_number_address_concat
- char_counter_street_address_concat
- Word Embedding

Model 
- Random forest
