### ISSUE TITLE
Create library on poetry

### ISSUE THREAD

**Issue by LeoSilvaGomes** [PDA-FGA/Playground#30]
### Description
After the spike about the poetry, we decided to start the library project effectively. **In this task** was expected to create and define the start of the **playground library**

### Outputs
- Account settings to the group
- List of names proposal
- Lib documentation
- Published lib

### Checklist
- [x] Create account to the project
- [ ] Define the project name
- [ ] Create documentation for the lib
    - [ ] Add explanation in the project - follow the instruction on this task (https://github.com/orgs/PDA-FGA/projects/1/views/1)
    - [ ] How to use
    - [ ] How to run

**Comment by Bruno-Felix** [comment]
pyproject.toml file documentation: [pyproject.toml
](https://python-poetry.org/docs/pyproject/)

**Comment by Bruno-Felix** [comment]
The documentation will be created at another time
