### ISSUE TITLE
Reestructure the repository to follow Lib pattern

### ISSUE THREAD

**Issue by LeoSilvaGomes** [PDA-FGA/Playground#33]
### Description
Based on the spike about the poetry was decided to restructure the repository to receive the poetry in the best way as possible. **In this task** should be a refactor in the project structure.

### Checklist
- [x] Migrate all test to specific `test` folder
- [x] Migrate `yaml` folder to `data` folder

**Comment by Bruno-Felix** [comment]
The conversation appeared in :Issue #20, commentary [Questions about Project Organization](https://github.com/PDA-FGA/Playground/issues/20#issuecomment-1366961563)

**Comment by Bruno-Felix** [comment]
The tests migrations way already did in others issues implementations
