### ISSUE TITLE
Automate the lib release

### ISSUE THREAD

**Issue by LeoSilvaGomes** [PDA-FGA/Playground#34]
### Description
Automate pipeline of library publish ✨ 

### Checklist
- [x] Create pipeline of library release
- [x] Create release documentation 
- [ ] Add comment step by step how to do it

**Comment by Bruno-Felix** [comment]
created a Repository secrets: PYPI_TOKEN

**Comment by Bruno-Felix** [comment]
## Release Template Documentation
This is the minimal template for describe the lib release

---

# Title (version)

## Description
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras suscipit est sit amet aliquam facilisis. Vestibulum vulputate, neque non pulvinar consequat, orci lorem sollicitudin urna, et accumsan erat metus dignissim massa. Nam sem diam, pellentesque vitae semper vel, fringilla id eros. Morbi condimentum urna et lorem viverra condimentum.

## New Features
- (#issue) Add ...
- (#issue) Add ...

## Improvements
- (#issue) Change ...
- (#issue) Change ... 

## Bug Fixes
- (#issue) Fix ... 
- (#issue) Fix ...

## Other Changes
- (#issue) Remove ...
- (#issue) Ajust ...

## Docs
- (#issue) Document ...
- (#issue) Document ...

---

#### In Release, also be necessary the Assets files

- poetry-1.3.0-py3-none-any.whl
- poetry-1.3.0.tar.gz 
- Source code (zip)
Source code (tar.gz)

--- 

@LeoSilvaGomes @alvesisaque opinions of any changes or improve?

**Comment by Bruno-Felix** [comment]
For Automate the lib release is necessary create a new actions when build and publish the new library of the version.

### Step by Spep

1. Develop all implementations;
2. When it is necessary to create a new version of the project, Change the `version` on `pyproject.toml`;
3. After this, Draft a New [Release](https://github.com/PDA-FGA/Playground/releases) following the release template;
4. After the published release, the actions will be run and the lib will be Build and Publish. Follow the process is very necessary.

**Comment by Bruno-Felix** [comment]
For Automate the lib release is necessary create a new actions when build and publish the new library of the version.
